errors:
  disabled: workflow или триггер отключён
  handleNotUnique: псевдоним workflow не уникален
  invalidHandle: неверный псевдоним
  invalidID: неверный ID
  notAllowedToCreate: нет прав создавать workflow
  notAllowedToDelete: нет прав удалять этот workflow
  notAllowedToExecute: нет прав запускать этот workflow
  notAllowedToExecuteCorredorStep: нет прав запускать функцию corredorExec, corredor отключён
  notAllowedToRead: нет прав просматривать этот workflow
  notAllowedToSearch: нет прав искать или просматривать workflows
  notAllowedToUndelete: нет прав восстанавливать этот workflow
  notAllowedToUpdate: нет прав обновлять этот workflow
  notFound: workflow не найден
  staleData: устаревшие данные
  unknownWorkflowStep: неизвестный шаг workflow
