errors:
  invalidID: Некорректный ID
  notAllowedToCreate: Нет прав на создание приложений
  notAllowedToDelete: Нет прав на удаление этого приложения
  notAllowedToManageFlag: Нет прав на управление флагами приложения
  notAllowedToManageFlagGlobal: Нет прав на управление глобальными флагами приложений
  notAllowedToRead: Нет прав на просмотр этого приложения
  notAllowedToSearch: Нет прав на поиск или просмотр приложений
  notAllowedToUndelete: Нет прав на восстановление этого приложения
  notAllowedToUpdate: Нет прав на изменение этого приложения
  notFound: Приложение не найдено
