---
errors:
  invalidID: неверный ID
  notAllowedToCreate: нет прав для создания приложений
  notAllowedToDelete: нет прав для удаления этого приложения
  notAllowedToManageFlag: нет прав для управления флагами приложений
  notAllowedToManageFlagGlobal: нет прав для управления глобальными флагами приложений
  notAllowedToRead: нет прав для просмотра этого приложения
  notAllowedToSearch: нет прав для поиска или просмотра приложений
  notAllowedToUndelete: нет прав для восстановления этого приложения
  notAllowedToUpdate: нет прав для изменения этого приложения
  notFound: приложение не найдено
