automation: Автоматизация
chart: Диаграммы
configuration: Настройки
editPage: Редактировать страницу
help:
  documentation: Документация
  feedback: Отправить отзыв
  forum: Помощь
  version: 'Версия:'
module: Модули
more: Ещё
namespace: Пространства имён
noPageTitle: Нет заголовка страницы
page: Страницы
appMenu: Меню
userSettings:
  changePassword: Сменить пароль
  loggedInAs: Вошли как {{user}}
  logout: Выйти
  profile: Профиль
viewPage: Просмотр страницы
