---
template:
  title: Безопасность
  password:
    title: Пароль
    change-link: Сменить пароль
  mfa:
    title: Многофакторная аутентификация
    totp:
      title: Дополнительная защита через мобильное приложение (одноразовый пароль по времени)
      enforced: Настроено и обязательно при входе.
      disabled: В данный момент отключено.
      configure: Настроить
      disable: Отключить
    email:
      title: Дополнительная защита через одноразовый пароль по email
      enforced: Включено и обязательно при входе.
      disabled: В данный момент отключено.
      enable: Настроить
      disable: Отключить
    all-disabled: Все методы MFA сейчас отключены. Обратитесь к администратору для их включения.
alerts:
  topt-disabled: Двухфакторная аутентификация с TOTP отключена
