errors:
  handleNotUnique: псевдоним не уникален
  invalidHandle: неверный псевдоним
  invalidID: неверный ID
  invalidNamespaceID: неверный или отсутствует ID пространства
  moduleNotFound: модуль не существует
  namespaceNotFound: пространство не существует
  notAllowedToCreate: нет прав создавать диаграммы
  notAllowedToDelete: нет прав удалять эту диаграмму
  notAllowedToRead: нет прав просматривать эту диаграмму
  notAllowedToReadNamespace: нет прав просматривать это пространство
  notAllowedToSearch: нет прав искать или просматривать диаграммы
  notAllowedToUndelete: нет прав восстанавливать эту диаграмму
  notAllowedToUpdate: нет прав обновлять эту диаграмму
  notFound: диаграмма не существует
  staleData: устаревшие данные
