configuration: Конфигурация
edge: Связь
name:
  label: Имя *
  placeholder: Название рабочего процесса
handle:
  label: Идентификатор
  placeholder: идентификатор (a - z, 0 - 9, подчёркивание, дефис)
  invalid-handle-characters: Должно быть не менее 2 символов. Можно использовать только буквы, цифры, подчёркивания и точки. Должно заканчиваться буквой или цифрой
description:
  label: Описание
  placeholder: Опишите, что делает этот рабочий процесс
target: Цель
tooltip:
  run-workflow: Запустить рабочий процесс
  configure-step: Настроить шаг
run-as:
  label: Выполнять как
  placeholder: Пользователь, который будет выполнять рабочий процесс
  description: Если явно не указано, процесс будет выполняться пользователем, который его запустил
sub-workflow:
  label: Вложенный процесс
  description: Вложенные процессы не могут иметь включённых триггеров
