automation:
  add: Добавить скрипт
  edit:
    asyncHelp: Не ждать результата и игнорировать ошибки. Несовместимо с флагом критичности.
    asyncLabel: Запустить этот скрипт асинхронно
    codeTabLabel: Код
    criticalHelp: Ждать выполнения скрипта. В случае ошибки прервать выполнение других скриптов и before* триггера
    criticalLabel: Критичный скрипт
    delete: Удалить скрипт
    enabledHelp: Отключённые скрипты будут игнорироваться
    enabledLabel: Включён
    mailAutomationTriggers:
      addMatcher: Добавить условие
      addTrigger: Добавить триггер
      delete: Удалить триггер
      deleteTrigger: Удалить
      enable: Включить триггер
      matchAll: Должны выполняться все условия
      matcher:
        fields:
          bcc: BCC
          cc: CC
          from: Отправитель
          placeholder: Заголовок письма
          replyTo: Ответить
          subject: Тема
          to: Кому
        match: Значение для сопоставления
        operators:
          equal-ci: Полное совпадение
          placeholder: Оператор
          prefix-ci: Совпадение по префиксу
          regex: Регулярное выражение
          suffix-ci: Совпадение по суффиксу
          user: Существующий пользователь
      tabLabel: Триггеры почты
    nameLabel: Имя
    namePlaceholder: Имя скрипта автоматизации
    runAsCurrentUser: Запустить как "{{ user }}"
    runAsHelp: Исполнитель скрипта
    scheduledTriggers:
      tabLabel: Scheduled
    securityLabel: Security
    settingsTabLabel: Settings
    timeoutHelp: How much time do we wait before aborting the script? Value in milliseconds (1000ms = 1s). It defaults (when 0) to 2s with 30s as maximum. Consult with your administrator for exact numbers and limitations.
    timeoutLabel: Script execution timeout
    timeoutPlaceholder: "1500"
    title: Automation script
    userPickerPlaceholder: Select user
  import: Import automation script(s)
  list:
    column:
      label:
        async: Асинхронно
        critical: Критичный
        enabled: Включён
        runAs: Запускать как
        runInUA: В браузере
    unnamed: (Безымянный скрипт)
  manage: Управлять скриптами автоматизации ({{count}})
  manage-id-permissions: Управлять правами для этого скрипта
  manage-wc-permissions: Управлять правами для всех скриптов
  newLabel: Создать новый скрипт
  newPlaceholder: Имя скрипта
  testing:
    load: Загрузить
    parametersHeadline: 'Параметры и данные:'
    resultsHeadline: 'Результаты:'
    testInBrowser: Тестировать в браузере
    testInCorredor: Тестировать в Corredor
    warning: ""
  title: Список скриптов автоматизации
general:
  resource-list:
    no-items: Нет совпадений по вашему запросу
  notFound: 'Не найдено'
  loading: Загрузка
  label:
    "no": "Нет"
    submit: Отправить
    "yes": "Да"
    selectOption: "Пожалуйста, выберите вариант"
  logout: Выйти
  noAccess: У вас нет прав для доступа к панели администратора
  pagination:
    next: Далее
    prev: Предыдущая
    showing: '{{from}} - {{to}} из {{count}} {{data}}'
    single_one: 'Один {{data}}'
    single_other: '{{count}} {{data}}'
navigation:
  appMenu: Меню
  adminPanel: Панель администратора
  automation: Автоматизация
  chart: Диаграммы
  configuration: Конфигурация
  help:
    documentation: Документация
    feedback: Отправить отзыв
    forum: Помощь
    version: 'Версия:'
  module: Модули
  more: Ещё
  namespace: Пространства
  noPageTitle: Нет заголовка страницы
  page: Страницы
  publicPages: Публичные страницы
  userSettings:
    changePassword: Сменить пароль
    loggedInAs: Вы вошли как {{user}}
    logout: Выйти
    profile: Профиль
picker:
  role:
    placeholder: Начните вводить для поиска ролей
  member:
    placeholder: Начните вводить для поиска пользователей
