editor:
  title: Системные настройки
  auth:
    title: Аутентификация
    url: URL
    internal:
      title: Внутренняя
      enabled: Внутренняя аутентификация включена
      password-reset:
        enabled: Сброс пароля включён
      password-constraints:
        title: Требования к паролю
        ignored-security: Система настроена на игнорирование требований к безопасности пароля, что небезопасно для продакшн-среды. Если это продакшн, обратитесь к администратору для обновления конфигурации (переменная AUTH_PASSWORD_SECURITY в .env).
        min-length: Минимальная длина
        min-length-description: Не менее 8 символов
        min-num-count: Минимальное количество цифр
        min-num-count-description: Пароль должен содержать не менее указанного количества цифр (отключено, если 0)
        min-special-count: Минимальное количество специальных символов
        min-special-count-description: Пароль должен содержать не менее указанного количества специальных символов (отключено, если 0)
        min-upper-case-length: Минимальное количество заглавных букв
        min-upper-case-description: Пароль должен содержать не менее указанного количества заглавных букв (отключено, если 0)
        min-lower-case-length: Минимальное количество строчных букв
        min-lower-case-description: Пароль должен содержать не менее указанного количества строчных букв (отключено, если 0)
      signup:
        email-confirmation-required: Требуется подтверждение email при регистрации
        enabled: Регистрация включена
        split-credentials-check:
          description: 'Вход разделён на два шага: сначала ввод email, затем — пароля. Пользователь автоматически перенаправляется к внешнему провайдеру, если у него нет пароля и есть только один IdP.'
          label: Включить разделённую проверку учётных данных
      profile-avatar:
        enabled: Аватар профиля включён
      send-user-invite-email:
        title: Пригласительное письмо
        enabled: Отправлять приглашение при создании пользователя
        description: При включении этой опции приглашение будет отправлено новому пользователю через CLI
        expires:
          label: Действительно
          description: Сколько времени токен приглашения будет действовать до истечения срока
    mail:
      title: Email для отправки писем аутентификации
      from-address: Адрес отправителя
      from-name: Имя отправителя
      validate-email: Пожалуйста, введите действительный email-адрес
    mfa:
      title: Многофакторная аутентификация
      TOTP:
        enabled: Разрешить пользователям использовать время-основанный одноразовый пароль (с помощью мобильного приложения)
        enforced: Вынудить пользователей использовать время-основанный одноразовый пароль (с помощью мобильного приложения)
        issuer:
          description: Имя издателя будет отправлено в приложение-аутентификатор, когда пользователь настраивает его
          label: Издатель
      emailOTP:
        enabled: Разрешить пользователям использовать одноразовый пароль по email
        enforced: Вынудить пользователей использовать одноразовый пароль по email
        expires:
          description: Сколько времени пароль будет действовать до истечения срока
          label: Действительно
    auto-logout:
      title: Автоматический выход
      enabled:
        label: Включено
        description: Автоматически выйти из системы пользователей после определенного периода неактивности
      timeout:
        label: Таймаут
        description: Период неактивности в секундах перед тем, как пользователь будет выведен из системы

  external:
    title: Внешние провайдеры аутентификации
    enabled: Включить внешнюю аутентификацию

    table:
      header:
        enabled: Включено
        provider: Провайдер
        info: Издатель, ключ клиента

    standard:
      enabled: Включено
      apiAccess: Доступ к API
      clientKey: Ключ клиента
      clientSecret: Секрет

    oidc:
      add: Добавить провайдер OIDC
      enabled: Включено
      handle: Обработчик
      title: OpenID Connect
      issuer: URL-адрес издателя OIDC
      issuerHint: Где найти /.well-known/openid-configuration (без /.well-known/openid-configuration)
      clientKey: Ключ клиента
      clientSecret: Секрет
      scope: Область
      scopePlaceholder: Список поддерживаемых значений области OAuth
      scopeHint: Использовать строку, разделенную пробелами

    saml:
      enabled: Включено
      title: SAML
      requests:
        title: Запросы
        sign-requests: Подписать запросы
        sign-method: Метод подписи
        binding: Привязка
        binding-redirect: HTTP Redirect
        binding-post: HTTP POST
      cert:
        public: Публичный ключ
        private: Приватный ключ
      name: Имя
      certificate: Сертификат
      idp:
        title: Провайдер удостоверений
        ident-handle: Поле обработчика
        ident-identifier: Поле идентификатора
        ident-name: Поле имени
        url: URL
      desc:
        name: Имя IdP, используемое на экране входа (Войти с помощью <имя>)
        cert:
          public: Содержимое будет минимизировано
          private: Содержимое будет минимизировано
        requests:
          sign-requests: Подписать AuthNRequest и утверждение
          sign-method: Метод, используемый для подписи запросов
          binding: Тип HTTP-привязки, используемой для AuthNRequest, по умолчанию HTTP Redirect (GET)
        idp:
          url: Расположение метаданных IdP
          ident-handle: Имя поля IdP, используемого для заполнения имени пользователя Corteza или nickname
          ident-identifier: Имя поля IdP, используемого для заполнения и сопоставления email пользователя Corteza
          ident-name: Имя поля IdP, используемого для заполнения полного имени пользователя Corteza

    security:
      title: Безопасность
      prohibited-roles:
        description: Роли из этого списка будут удалены из контекста безопасности при аутентификации с помощью этого провайдера
        label: Запрещенные роли
      forced-roles:
        description: Роли из этого списка всегда будут добавлены в контекст безопасности при аутентификации с помощью этого провайдера
        label: Вынужденные роли
      permitted-roles:
        description: Только роли из этого списка будут добавлены в контекст безопасности при аутентификации с помощью этого провайдера
        label: Разрешенные роли

  bgScreen:
    title: Экран аутентификации

    image:
      uploader:
        label: Фоновое изображение
        instructions: Нажмите или перетащите фоновое изображение для загрузки
        uploading: Загрузка фонового изображения аутентификации

      editor:
        label: Пользовательский CSS