editor:
  info:
    createdAt: Создано
    createdBy: Создал
    delete: Удалить
    deletedAt: Удалено
    enabled: Включён
    id: ID
    name: Имя *
    title: Основная информация
    undelete: Восстановить
    updatedAt: Обновлено
  new: Новое приложение
  permissions: Права
  title:
    create: Создать приложение
    edit: Редактировать приложение
  unify:
    config:
      description: Конфигурация приложения (JSON)
      label: Конфигурация
    listed: В списке
    logo:
      label: Логотип
      description: Логотип, используемый в селекторе приложений
      placeholder: Выберите логотип или перетащите сюда...
      reset: Сбросить
    name:
      description: Имя, используемое в селекторе приложений
      label: Имя
    pinned: Закреплено
    title: Селектор приложений
    url:
      description: URL приложения
      label: URL
list:
  columns:
    actions: ""
    createdAt: Создано
    enabled: Включён
    name: Имя
    appListName: Имя в селекторе приложений
    state: Состояние
  export: Экспорт
  rows:
    filters:
      deleted: Удалено
  filterForm:
    deleted:
      label: удаленные приложения
    excluded:
      label: Без
    exclusive:
      label: Только
    inclusive:
      label: Включая
    query:
      label: Фильтр списка приложений
      placeholder: Фильтр приложений по имени
  loading: Загрузка приложений
  new: Новое приложение
  numFound: '{{count}} приложение найдено'
  numFound_plural: '{{count}} приложений найдено'
  permissions: Права
  title: Приложения
  yaml: YAML
  delete: Удалить
  undelete: Восстановить
