---
editor:
  title: 'Настройки пользовательского интерфейса'
  mainLogo:
    title: 'Основной логотип'
    uploader:
      instructions: 'Кликните или перетащите основной логотип сюда для загрузки'
      uploading: 'Загрузка основного логотипа'
  iconLogo:
    title: 'Иконка-логотип'
    uploader:
      instructions: 'Кликните или перетащите иконку-логотип сюда для загрузки'
      uploading: 'Загрузка иконки-логотипа'
  favicon:
    title: 'Фавикон'
    uploader:
      instructions: 'Кликните или перетащите файл фавикона сюда для загрузки'
      uploading: 'Загрузка фавикона'
